name: Compile Latex and Release PDF  

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile Slides
        uses: xu-cheng/latex-action@v2
        with:
          root_file: slides/main.tex

      - name: Compile First Workshop
        uses: xu-cheng/latex-action@v2
        with:
          root_file: practice-1/main.tex

      - name: Check PDFs
        run: |
          test -f slides/main.pdf
          test -f practice-1/main.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Slides PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: slides/main.pdf
          asset_name: lectures-slides-${{ github.ref_name }}.pdf
          asset_content_type: application/pdf

      - name: Upload Workshop PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: practice-1/main.pdf
          asset_name: practice-1-${{ github.ref_name }}.pdf
          asset_content_type: application/pdf